version: 2
updates:
  # Root project npm dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
